<?php
session_start();require __DIR__.'/includes/functions.php';
if($_SERVER['REQUEST_METHOD']!=='POST'){header('Location:/contact');exit;}
if(!empty($_POST['_website'])){header('Location:/');exit;}
$now=time();if(!empty($_SESSION['last_enquiry_at'])&&($now-(int)$_SESSION['last_enquiry_at'])<5){http_response_code(429);exit('Please wait a few seconds before submitting again.');}$_SESSION['last_enquiry_at']=$now;
$name=trim($_POST['name']??'');$email=trim($_POST['email']??'');$phone=trim($_POST['phone']??'');$trip=trim($_POST['trip']??($_POST['interest']??''));$message=trim($_POST['message']??'');
if(!$name||strlen($name)>120||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>190){http_response_code(422);exit('Please provide a valid name and email.');}
$extras=[];if(!empty($_POST['arrival_date']))$extras[]='Arrival: '.trim($_POST['arrival_date']);if(!empty($_POST['departure_date']))$extras[]='Departure: '.trim($_POST['departure_date']);if(!empty($_POST['travelers']))$extras[]='Travelers: '.max(1,(int)$_POST['travelers']);if(!empty($_POST['interests'])&&is_array($_POST['interests'])){$allowed=['Safari','Kilimanjaro','Trekking','Zanzibar','Culture / Day Trips','Chimpanzee Trekking'];$interests=array_values(array_intersect($allowed,$_POST['interests']));if($interests)$extras[]='Interests: '.implode(', ',$interests);}if($extras)$message=implode("\n",$extras).($message?"\n\n$message":'');
$cfg=site_config();$pdo=db();if($pdo){try{$st=$pdo->prepare('INSERT INTO enquiries(name,email,phone,trip,message,created_at) VALUES(?,?,?,?,?,NOW())');$st->execute([$name,substr($email,0,190),substr($phone,0,80),substr($trip,0,190),$message]);}catch(Throwable $e){}}
$subject='Website enquiry: '.preg_replace('/[\r\n]+/',' ',($trip?:'Tanzania trip'));$body="Name: $name\nEmail: $email\nPhone: $phone\nTrip: $trip\n\n$message";$headers="Reply-To: $email\r\nContent-Type: text/plain; charset=UTF-8\r\n";@mail($cfg['site']['email'],$subject,$body,$headers);if(!empty($cfg['site']['email2']))@mail($cfg['site']['email2'],$subject,$body,$headers);
$pageMeta=meta('Enquiry Received','Thank you for contacting Tanzania Wildlife Epic.');require __DIR__.'/includes/header.php';?><main><section class="section wrap center"><span class="eyebrow dark-text">Thank you</span><h1>Your enquiry has been received</h1><p>We have your trip request. For a quicker conversation you can also continue on WhatsApp.</p><a class="btn gold" target="_blank" rel="noopener" href="<?=e(wa_link('Hello Tanzania Wildlife Epic, I have just submitted an enquiry from the website.'))?>">Continue on WhatsApp</a></section></main><?php require __DIR__.'/includes/footer.php';
