<?php require __DIR__.'/includes/functions.php';require __DIR__.'/includes/data.php';$pageMeta=meta('Tanzania Safaris, Kilimanjaro & Zanzibar','Plan Tanzania safaris, Kilimanjaro treks, Zanzibar extensions and selected day trips with Tanzania Wildlife Epic.');require __DIR__.'/includes/header.php';$pk=packages();?>
<main><section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">Tanzania Wildlife Epic</span><h1>Experience Tanzania, Your Way</h1><p>Safari planning, mountain trekking and island extensions built around the places you actually want to explore.</p><div class="hero-actions"><a class="btn gold" href="/safaris">Explore Safaris</a><a class="btn ghost" href="/contact">Plan Your Trip</a></div></div><form class="quote-card" action="/enquiry.php" method="post"><h2>Plan Your Trip</h2><input name="name" placeholder="Your name" required><input type="email" name="email" placeholder="Email" required><select name="interest"><option>Safari</option><option>Kilimanjaro</option><option>Zanzibar</option><option>Day Trip</option></select><button class="btn dark">Start Planning</button></form></div></section>
<section class="intro-strip"><div class="wrap three"><article><h3>Tanzania Safaris</h3><p>Explore Serengeti, Ngorongoro, Tarangire and wider Tanzania circuits.</p><a href="/safaris">View safaris →</a></article><article><h3>Kilimanjaro</h3><p>Compare routes and trip lengths with clear day-by-day itineraries.</p><a href="/kilimanjaro">Explore climbs →</a></article><article><h3>Zanzibar</h3><p>Add Indian Ocean rest, culture and beach time after safari or trekking.</p><a href="/zanzibar">Discover Zanzibar →</a></article></div></section>
<section class="section wrap"><span class="eyebrow dark-text">Popular Tanzania Trips</span><h2>Start with a proven itinerary structure</h2><div class="cards"><?php foreach(array_slice($pk,0,4) as $p):?><article class="trip-card"><div class="trip-img"></div><div class="trip-body"><span><?=e($p['days'])?> day<?= $p['days']==1?'':'s' ?> · <?=e($p['category'])?></span><h3><?=e($p['title'])?></h3><p><?=e($p['summary'])?></p><div class="card-actions"><a href="/package/<?=e($p['slug'])?>">View itinerary</a><a href="/contact">Request a Quote</a></div></div></article><?php endforeach;?></div></section>
<section class="split dark-section"><div class="split-photo"></div><div class="split-copy"><span class="eyebrow">Tailor-made planning</span><h2>Build the trip around your time in Tanzania</h2><p>Combine safari, trekking, cultural stops and Zanzibar without forcing every traveler into the same sequence.</p><a class="btn gold" href="/contact">Plan My Tanzania Trip</a></div></section>
<section class="section wrap"><div class="section-head"><div><span class="eyebrow dark-text">Mountain Climbing</span><h2>Kilimanjaro & Trekking</h2></div><a href="/kilimanjaro">See all routes →</a></div><div class="feature-grid"><a class="feature-card tall" href="/package/7-days-machame-route"><strong>7 Days Machame Route</strong><span>View itinerary</span></a><a class="feature-card" href="/package/mount-meru-4-days"><strong>Mount Meru</strong><span>4-day trek</span></a><a class="feature-card" href="/trekking"><strong>More Trekking</strong><span>Explore Tanzania on foot</span></a></div></section>
<section class="section soft"><div class="wrap"><div class="section-head"><div><span class="eyebrow dark-text">Discover Tanzania</span><h2>Destinations to connect into your itinerary</h2></div><a href="/destinations">All destinations →</a></div><div class="destination-row"><?php foreach(array_slice(destinations(),0,5) as $d):?><a href="/destinations#<?=e($d['slug'])?>"><strong><?=e($d['name'])?></strong></a><?php endforeach;?></div></div></section>
<section class="section wrap"><div class="section-head"><div><span class="eyebrow dark-text">Add-on Adventures</span><h2>Day trips and short experiences</h2></div><a href="/day-trips">View day trips →</a></div><div class="cards compact"><?php foreach(array_slice($pk,-2) as $p):?><article class="trip-card"><div class="trip-body"><h3><?=e($p['title'])?></h3><p><?=e($p['summary'])?></p><a href="/package/<?=e($p['slug'])?>">View details →</a></div></article><?php endforeach;?></div></section>
<section class="why"><div class="wrap"><span class="eyebrow">Why book with Tanzania Wildlife Epic</span><h2>Clear planning. Tanzania focus. No invented promises.</h2><div class="three"><article><h3>One Tanzania specialist</h3><p>Plan safari, trekking and Zanzibar within one connected itinerary.</p></article><article><h3>Transparent trip structure</h3><p>Every package follows a consistent overview, summary, daily itinerary and inclusions format.</p></article><article><h3>Flexible enquiries</h3><p>Where pricing is not verified, the site asks you to request a quote instead of showing made-up rates.</p></article></div></div></section>
<section class="section wrap"><span class="eyebrow dark-text">Frequently Asked Questions</span><h2>Planning your Tanzania journey</h2><div class="faq"><details><summary>Can I combine safari and Zanzibar?</summary><p>Yes. Enquire with your intended dates and trip length so the sequence can be planned around your priorities.</p></details><details><summary>Do all packages have fixed prices?</summary><p>No. Unverified pricing is intentionally replaced with Request a Quote.</p></details><details><summary>Can I add Kilimanjaro to a safari?</summary><p>Yes. A combined itinerary can be structured around the climb, recovery time and safari route.</p></details></div></section>
</main><?php require __DIR__.'/includes/footer.php';?>
