<?php
$root=dirname(__DIR__);$cfgFile=$root.'/config.php';$cfg=file_exists($cfgFile)?require $cfgFile:require $root.'/config.example.php';$db=$cfg['db'];$msg='';
try{$pdo=new PDO("mysql:host={$db['host']};dbname={$db['name']};charset=utf8mb4",$db['user'],$db['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES,false);
$schema=[
"CREATE TABLE IF NOT EXISTS admins(id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,role VARCHAR(40) DEFAULT 'admin',created_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS enquiries(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(190) NOT NULL,phone VARCHAR(80),trip VARCHAR(190),message TEXT,status VARCHAR(30) DEFAULT 'new',created_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS packages(id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(190) UNIQUE NOT NULL,title VARCHAR(220) NOT NULL,category VARCHAR(80) NOT NULL,duration_days INT NOT NULL,tour_type VARCHAR(120),location VARCHAR(190),summary TEXT,overview MEDIUMTEXT,inclusions MEDIUMTEXT,exclusions MEDIUMTEXT,important_notes MEDIUMTEXT,featured_image VARCHAR(255),status ENUM('draft','published') DEFAULT 'draft',meta_title VARCHAR(190),meta_description VARCHAR(255),sort_order INT DEFAULT 0,updated_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS itinerary_days(id INT AUTO_INCREMENT PRIMARY KEY,package_id INT NOT NULL,day_number INT NOT NULL,title VARCHAR(220) NOT NULL,body MEDIUMTEXT NOT NULL,accommodation VARCHAR(220),meals VARCHAR(220),altitude VARCHAR(120),drive_time VARCHAR(120),image VARCHAR(255),UNIQUE KEY uniq_day(package_id,day_number),CONSTRAINT fk_itin_pkg FOREIGN KEY(package_id) REFERENCES packages(id) ON DELETE CASCADE)",
"CREATE TABLE IF NOT EXISTS pages(id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(190) UNIQUE NOT NULL,title VARCHAR(190) NOT NULL,body MEDIUMTEXT,status ENUM('draft','published') DEFAULT 'draft',featured_image VARCHAR(255),meta_title VARCHAR(190),meta_description VARCHAR(255),updated_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS destinations(id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(190) UNIQUE NOT NULL,name VARCHAR(190) NOT NULL,summary TEXT,body MEDIUMTEXT,featured_image VARCHAR(255),status ENUM('draft','published') DEFAULT 'draft',meta_title VARCHAR(190),meta_description VARCHAR(255),updated_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS articles(id INT AUTO_INCREMENT PRIMARY KEY,slug VARCHAR(190) UNIQUE NOT NULL,title VARCHAR(220) NOT NULL,excerpt TEXT,body MEDIUMTEXT,featured_image VARCHAR(255),status ENUM('draft','published') DEFAULT 'draft',published_at DATETIME NULL,meta_title VARCHAR(190),meta_description VARCHAR(255),updated_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS faqs(id INT AUTO_INCREMENT PRIMARY KEY,question VARCHAR(255) NOT NULL,answer TEXT NOT NULL,category VARCHAR(80),sort_order INT DEFAULT 0,status ENUM('draft','published') DEFAULT 'published')",
"CREATE TABLE IF NOT EXISTS media(id INT AUTO_INCREMENT PRIMARY KEY,file_name VARCHAR(255) NOT NULL,path VARCHAR(255) NOT NULL,mime_type VARCHAR(100),alt_text VARCHAR(255),width INT,height INT,file_size INT,created_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS redirects(id INT AUTO_INCREMENT PRIMARY KEY,old_path VARCHAR(255) UNIQUE NOT NULL,new_path VARCHAR(255) NOT NULL,status_code SMALLINT DEFAULT 301,created_at DATETIME NOT NULL)",
"CREATE TABLE IF NOT EXISTS settings(setting_key VARCHAR(120) PRIMARY KEY,setting_value MEDIUMTEXT,updated_at DATETIME NOT NULL)"
];foreach($schema as $sql){$pdo->exec($sql);}if($_SERVER['REQUEST_METHOD']==='POST'){$email=trim($_POST['email']??'');$pass=$_POST['password']??'';if(filter_var($email,FILTER_VALIDATE_EMAIL)&&strlen($pass)>=10){$st=$pdo->prepare('INSERT INTO admins(email,password_hash,role,created_at) VALUES(?,?,?,NOW()) ON DUPLICATE KEY UPDATE email=email');$st->execute([$email,password_hash($pass,PASSWORD_DEFAULT),'admin']);$msg='Database ready and admin created. Delete or rename this setup file now.';}else{$msg='Use a valid email and a password of at least 10 characters.';}}else{$msg='Database tables are ready. Create the first admin below.';}}catch(Throwable $e){$msg='Database setup failed. Check config.php, database existence, and database privileges.';}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="/assets/css/style.css"><title>TWE Setup</title></head><body><main class="section wrap narrow"><h1>Tanzania Wildlife Epic Setup</h1><p><?=htmlspecialchars($msg)?></p><form class="contact-form" method="post"><input type="email" name="email" placeholder="Admin email" required><input type="password" name="password" placeholder="Admin password (10+ characters)" required><button class="btn gold">Create Admin</button></form><p><strong>Security:</strong> remove or rename this file immediately after successful setup.</p></main></body></html>
