<?php
function packages(){return [
['slug'=>'7-days-tanzania-luxury-safari','title'=>'7 Days Tanzania Luxury Safari','days'=>7,'type'=>'Private Safari','location'=>'Northern Tanzania','category'=>'Safari','summary'=>'A carefully paced private safari linking Tarangire, Serengeti and Ngorongoro with a premium, flexible travel rhythm.','itinerary'=>[
['title'=>'Arrival and safari briefing','text'=>'Meet the Tanzania Wildlife Epic team, review the route and prepare for the safari ahead.'],['title'=>'Tarangire National Park','text'=>'Travel into Tarangire for game viewing among baobab landscapes and seasonal wildlife concentrations.'],['title'=>'Serengeti National Park','text'=>'Continue toward the Serengeti and begin exploring its open plains.'],['title'=>'Serengeti safari','text'=>'A full day exploring different Serengeti habitats with routing adapted to conditions and season.'],['title'=>'Serengeti to Ngorongoro','text'=>'Enjoy a final Serengeti game drive before continuing toward the Ngorongoro highlands.'],['title'=>'Ngorongoro Crater','text'=>'Descend into the Ngorongoro Crater for game viewing in the caldera ecosystem.'],['title'=>'Return / onward arrangements','text'=>'Complete the safari and continue toward your onward travel arrangements.']]],
['slug'=>'4-days-tanzania-group-safari','title'=>'4 Days Tanzania Group Safari','days'=>4,'type'=>'Group Safari','location'=>'Northern Tanzania','category'=>'Safari','summary'=>'A compact northern circuit safari for travelers who want to share transport while visiting major wildlife areas.','itinerary'=>[['title'=>'Tarangire','text'=>'Begin with a game drive in Tarangire National Park.'],['title'=>'Serengeti','text'=>'Travel to Serengeti National Park and explore the plains.'],['title'=>'Serengeti to Ngorongoro','text'=>'Morning wildlife viewing then continue to the Ngorongoro area.'],['title'=>'Ngorongoro Crater','text'=>'Crater game drive followed by return arrangements.']]],
['slug'=>'7-days-machame-route','title'=>'7 Days Kilimanjaro Climb — Machame Route','days'=>7,'type'=>'Trekking','location'=>'Mount Kilimanjaro','category'=>'Kilimanjaro','summary'=>'A seven-day Machame itinerary with gradual altitude gain and a varied approach to Kilimanjaro.','itinerary'=>[['title'=>'Machame Gate to Machame Camp','text'=>'Start the climb through montane forest.'],['title'=>'Machame Camp to Shira Camp','text'=>'Ascend toward the Shira Plateau.'],['title'=>'Shira to Barranco via Lava Tower','text'=>'Use a higher point for acclimatization before descending to Barranco.'],['title'=>'Barranco to Karanga','text'=>'Cross the Barranco Wall and continue to Karanga.'],['title'=>'Karanga to Barafu','text'=>'Reach the high camp and prepare for summit night.'],['title'=>'Summit attempt and descent','text'=>'Climb toward Uhuru Peak, conditions permitting, then descend to lower camp.'],['title'=>'Final descent','text'=>'Complete the descent and exit through the park gate.']]],
['slug'=>'mount-meru-4-days','title'=>'4 Days Mount Meru Trek','days'=>4,'type'=>'Trekking','location'=>'Arusha National Park','category'=>'Trekking','summary'=>'A four-day Mount Meru trek through forest, heath and volcanic terrain.','itinerary'=>[['title'=>'Park gate to mountain hut','text'=>'Enter Arusha National Park and begin the ascent.'],['title'=>'Acclimatization and higher hut','text'=>'Continue upward with acclimatization built into the day.'],['title'=>'Summit attempt and descent','text'=>'Make the summit attempt subject to mountain and park conditions, then descend.'],['title'=>'Final descent','text'=>'Return to the park gate and complete the trek.']]],
['slug'=>'zanzibar-beach-extension','title'=>'Zanzibar Beach Extension','days'=>5,'type'=>'Beach Holiday','location'=>'Zanzibar','category'=>'Zanzibar','summary'=>'A flexible Zanzibar extension focused on coast, culture and rest after safari or trekking.','itinerary'=>[['title'=>'Arrival in Zanzibar','text'=>'Transfer to your arranged accommodation.'],['title'=>'Stone Town and culture','text'=>'Explore historic Zanzibar at your own pace or with arranged guiding.'],['title'=>'Coastal day','text'=>'Relax on the coast or add a suitable optional excursion.'],['title'=>'Free beach day','text'=>'Keep the day open for rest or locally arranged activities.'],['title'=>'Departure','text'=>'Transfer for onward travel.']]],
['slug'=>'materuni-waterfalls-day-trip','title'=>'Materuni Waterfalls Day Trip','days'=>1,'type'=>'Day Trip','location'=>'Kilimanjaro Region','category'=>'Day Trips','summary'=>'A day visit in the Kilimanjaro foothills combining a waterfall walk with local cultural context.','itinerary'=>[['title'=>'Materuni day experience','text'=>'Travel from the Moshi area to Materuni, walk toward the waterfall and enjoy a locally guided experience before returning.']]],
['slug'=>'kikuletwa-hot-springs-day-trip','title'=>'Kikuletwa Hot Springs Day Trip','days'=>1,'type'=>'Day Trip','location'=>'Kilimanjaro Region','category'=>'Day Trips','summary'=>'A relaxed day trip from northern Tanzania to the clear waters of Kikuletwa.','itinerary'=>[['title'=>'Kikuletwa visit','text'=>'Drive to Kikuletwa, spend time by the spring and return later in the day.']]]
];}
function destinations(){return [
['slug'=>'serengeti','name'=>'Serengeti National Park','text'=>'Tanzania’s best-known savannah ecosystem and a central part of many northern circuit itineraries.'],['slug'=>'ngorongoro','name'=>'Ngorongoro Crater','text'=>'A compact wildlife destination set within the Ngorongoro Conservation Area.'],['slug'=>'tarangire','name'=>'Tarangire National Park','text'=>'Known for baobab landscapes, riverine habitat and strong seasonal wildlife concentrations.'],['slug'=>'lake-manyara','name'=>'Lake Manyara National Park','text'=>'A varied Rift Valley park combining groundwater forest, escarpment scenery and lake-edge habitat.'],['slug'=>'kilimanjaro','name'=>'Mount Kilimanjaro','text'=>'Africa’s highest mountain and Tanzania’s most recognized trekking objective.'],['slug'=>'zanzibar','name'=>'Zanzibar','text'=>'An Indian Ocean archipelago suited to beach extensions, culture and post-safari relaxation.'],['slug'=>'nyerere','name'=>'Nyerere National Park','text'=>'A major southern Tanzania wilderness destination.'],['slug'=>'ruaha','name'=>'Ruaha National Park','text'=>'A remote southern circuit park with broad landscapes and a less crowded safari feel.'],['slug'=>'mahale','name'=>'Mahale Mountains','text'=>'A western Tanzania destination associated with Lake Tanganyika and chimpanzee trekking.'],['slug'=>'katavi','name'=>'Katavi National Park','text'=>'A remote western Tanzania safari destination suited to travelers seeking a wilder circuit.']
];}
