<?php
function e($v){return htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');}
function site_config(){static $c;if($c)return $c;$f=__DIR__.'/../config.php';$c=file_exists($f)?require $f:require __DIR__.'/../config.example.php';return $c;}
function db(){static $pdo;if($pdo instanceof PDO)return $pdo;$d=site_config()['db'];try{$pdo=new PDO("mysql:host={$d['host']};dbname={$d['name']};charset=utf8mb4",$d['user'],$d['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);return $pdo;}catch(Throwable $e){return null;}}
function wa_link($m='Hello Tanzania Wildlife Epic, I would like to plan a trip to Tanzania.'){$n=site_config()['site']['whatsapp'];return 'https://wa.me/'.$n.'?text='.rawurlencode($m);}
function current_url(){ $s=(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')?'https':'http';return $s.'://'.($_SERVER['HTTP_HOST']??'localhost').($_SERVER['REQUEST_URI']??'/');}
function package_by_slug($slug){$pdo=db();if($pdo){try{$st=$pdo->prepare("SELECT * FROM packages WHERE slug=? AND status='published' LIMIT 1");$st->execute([$slug]);if($row=$st->fetch()){$days=$pdo->prepare('SELECT * FROM itinerary_days WHERE package_id=? ORDER BY day_number');$days->execute([$row['id']]);$row['days']=(int)$row['duration_days'];$row['type']=$row['tour_type'];$row['itinerary']=array_map(fn($d)=>['title'=>$d['title'],'text'=>$d['body'],'accommodation'=>$d['accommodation']??'','meals'=>$d['meals']??'','altitude'=>$d['altitude']??'','drive_time'=>$d['drive_time']??''],$days->fetchAll());return $row;}}catch(Throwable $e){}}foreach(packages() as $p){if($p['slug']===$slug)return $p;}return null;}
function all_public_packages(){ $pdo=db();if($pdo){try{$rows=$pdo->query("SELECT * FROM packages WHERE status='published' ORDER BY sort_order,title")->fetchAll();if($rows){return array_map(function($r){$r['days']=(int)$r['duration_days'];$r['type']=$r['tour_type'];return $r;},$rows);}}catch(Throwable $e){}}return packages();}
function published_page($slug){$pdo=db();if(!$pdo)return null;try{$st=$pdo->prepare("SELECT * FROM pages WHERE slug=? AND status='published' LIMIT 1");$st->execute([$slug]);return $st->fetch()?:null;}catch(Throwable $e){return null;}}
function published_articles(){ $pdo=db();if(!$pdo)return [];try{return $pdo->query("SELECT * FROM articles WHERE status='published' ORDER BY published_at DESC,updated_at DESC")->fetchAll();}catch(Throwable $e){return [];}}
function redirect_if_needed(){ $path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH);$pdo=db();if(!$pdo)return;try{$st=$pdo->prepare('SELECT * FROM redirects WHERE old_path=? LIMIT 1');$st->execute([$path]);if($r=$st->fetch()){header('Location: '.$r['new_path'],true,(int)$r['status_code']);exit;}}catch(Throwable $e){}}
function meta($title,$description,$canonical=null){$site=site_config()['site'];$full=$title.' | '.$site['name'];$url=$canonical?:current_url();return '<title>'.e($full).'</title><meta name="description" content="'.e($description).'"><link rel="canonical" href="'.e($url).'"><meta property="og:type" content="website"><meta property="og:title" content="'.e($full).'"><meta property="og:description" content="'.e($description).'"><meta property="og:url" content="'.e($url).'"><meta name="twitter:card" content="summary_large_image">';}
