<?php redirect_if_needed();$cfg=site_config()['site']; ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><?php echo $pageMeta??''; ?><link rel="stylesheet" href="/assets/css/style.css"><link rel="stylesheet" href="/assets/css/overrides.css"><script defer src="/assets/js/app.js"></script></head><body>
<div class="topbar"><div class="wrap"><span><?=e($cfg['phone'])?></span><span><?=e($cfg['email'])?></span><span><?=e($cfg['location'])?></span></div></div>
<header class="site-header"><div class="wrap nav-wrap"><a class="brand" href="/"><span class="brand-mark">TWE</span><span><strong>Tanzania Wildlife Epic</strong><small>Safari • Kilimanjaro • Zanzibar</small></span></a><button class="menu-btn" aria-label="Open menu">☰</button><nav class="desktop-nav">
<div class="nav-item"><button>All Tours</button><div class="mega wide"><div><span class="mega-label">Epic Adventures</span><a href="/safaris">Tanzania Safari Tours</a><a href="/trekking">Chimpanzee Trekking Tours</a><a href="/day-trips">Tanzania Cycling Tours</a><a href="/day-trips">Cultural &amp; Day Trip Tours</a></div><div><span class="mega-label">Peaks &amp; Paradises</span><a href="/kilimanjaro">Mt. Kilimanjaro Tours</a><a href="/package/mount-meru-4-days">Mt. Meru Hiking Tours</a><a href="/zanzibar">Beach Holiday Tours</a></div></div></div>
<div class="nav-item"><button>Discover Tanzania</button><div class="mega wide"><div><span class="mega-label">The Iconic North &amp; Coast</span><a href="/destination/serengeti">Serengeti National Park</a><a href="/destination/ngorongoro">Ngorongoro Crater</a><a href="/destination/tarangire">Tarangire National Park</a><a href="/destination/lake-manyara">Lake Manyara National Park</a><a href="/destination/kilimanjaro">Mount Kilimanjaro</a><a href="/destination/zanzibar">Zanzibar Archipelago</a></div><div><span class="mega-label">Wild Frontiers</span><a href="/destination/nyerere">Southern Circuit</a><a href="/destination/mahale">Western Circuit</a><a href="/destinations">View All Destinations →</a></div></div></div>
<div class="nav-item"><button>Tanzania Safari</button><div class="mega wide"><div><span class="mega-label">Safari Styles</span><a href="/migration-safaris">Migration Safari</a><a href="/luxury-safaris">Luxury Safari</a><a href="/safaris">Mid-Range Safari</a><a href="/safaris">Budget Safari</a><a href="/safaris">Honeymoon Safari</a><a href="/family-safaris">Family Safari</a><a href="/day-trips">Day Trips</a></div><div><span class="mega-label">Travel Planner</span><a href="/destinations">Places to Visit</a><a href="/day-trips">Things to Do</a><a href="/travel-guide">Best Time to Visit</a><a href="/faq">Top Safari FAQs</a><a href="/travel-guide">Our Safari Articles</a></div></div></div>
<div class="nav-item"><button>Mountain Climbing</button><div class="mega wide"><div><span class="mega-label">Tanzania Peaks &amp; Treks</span><a href="/kilimanjaro">Kilimanjaro Trekking</a><a href="/kilimanjaro">Kilimanjaro Group Joining</a><a href="/kilimanjaro">Full Moon Climbs</a><a href="/package/mount-meru-4-days">Climbing Mount Meru</a><a href="/trekking">Mount Ol Doinyo Lengai</a><a href="/trekking">Usambara Mountain Trekking</a></div><div><span class="mega-label">Summit Planner</span><a href="/travel-guide">Before You Climb</a><a href="/travel-guide">Before You Arrive</a><a href="/travel-guide">When On The Mountain</a><a href="/travel-guide">Mountain Hiking Tips</a><a href="/faq">Kilimanjaro FAQs</a></div></div></div>
<a href="/zanzibar">Zanzibar</a><div class="nav-item"><button>About Us</button><div class="mega"><span class="mega-label">Our Company</span><a href="/about">Tanzania Wildlife Epic</a><a href="/about">Our Guides &amp; Porters</a><a href="/about">Social Impact &amp; Eco-Tourism</a><a href="/terms">Terms &amp; Conditions</a><span class="mega-label">Plan With Us</span><a href="/contact">Get a Custom Quote</a><a href="/contact">Contact Our Experts</a></div></div><a href="/search" aria-label="Search">Search</a><a class="nav-cta" href="/contact">Inquire Now</a></nav></div>
<div class="mobile-panel"><strong>Explore Tanzania Wildlife Epic</strong><a href="/safaris">All Tours</a><a href="/destinations">Discover Tanzania</a><a href="/safaris">Tanzania Safari</a><a href="/kilimanjaro">Mountain Climbing</a><a href="/zanzibar">Zanzibar</a><a href="/day-trips">Day Trips</a><a href="/travel-guide">Travel Guide</a><a href="/search">Search</a><a href="/about">About Us</a><a href="/contact">Inquire Now</a></div></header>
